### ISSUE TITLE
FileNotFoundException for bad username/login id input

### ISSUE THREAD

**Issue by ianarsenault** [GorgonsMaze/Github-Searcher#2]
When user opens application and enters in a "bad" Github Username, program is killed

```
09-11 04:17:32.784 30996-31197/com.githubsearch.githubsearch E/NO FILE:: java.io.FileNotFoundException: https://api.github.com/users/dkdkdkdkddkdkdkd34
09-11 04:17:32.784 30996-31197/com.githubsearch.githubsearch E/JSON Parser: Error parsing data org.json.JSONException: End of input at character 0 of 
09-11 04:17:33.344 30996-31197/com.githubsearch.githubsearch E/NO FILE:: java.io.FileNotFoundException: https://api.github.com/users/dkdkdkdkddkdkdkd34/repos
09-11 04:17:33.344 30996-31197/com.githubsearch.githubsearch E/JSON Parser: Error parsing data org.json.JSONException: End of input at character 0 of 
09-11 04:17:33.964 30996-31197/com.githubsearch.githubsearch E/NO FILE:: java.io.FileNotFoundException: https://api.github.com/users/dkdkdkdkddkdkdkd34/starred
09-11 04:17:33.964 30996-31197/com.githubsearch.githubsearch E/JSON Parser: Error parsing data org.json.JSONException: End of input at character 0 of 
09-11 04:17:33.964 30996-30996/com.githubsearch.githubsearch I/INFO: [Lorg.json.JSONObject;@a7f11840
09-11 04:17:33.964 30996-30996/com.githubsearch.githubsearch D/AndroidRuntime: Shutting down VM
09-11 04:17:33.964 30996-30996/com.githubsearch.githubsearch W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa6648228)
09-11 04:17:33.964 30996-30996/com.githubsearch.githubsearch E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               java.lang.NullPointerException
                                                                                   at com.githubsearch.githubsearch.MainActivity$RetrieveUserInfo.onPostExecute(MainActivity.java:109)
                                                                                   at com.githubsearch.githubsearch.MainActivity$RetrieveUserInfo.onPostExecute(MainActivity.java:68)
                                                                                   at android.os.AsyncTask.finish(AsyncTask.java:631)
                                                                                   at android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                                                   at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                   at android.os.Looper.loop(Looper.java:137)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                                   at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ianarsenault** [comment]
Fixed in [4b7a738](https://github.com/GorgonsMaze/Github-Searcher/commit/4b7a738a75b63d03f193e2f7686ca809c25f2c2d)
